#--------------------------------------------------------------------------------
# Standard Software Carpentry settings - should not need to be modified.
#--------------------------------------------------------------------------------
swc_blog        : "https://software-carpentry.org/feed.xml"
swc_contact     : "admin@software-carpentry.org"
swc_files       : "https://files.software-carpentry.org"
swc_github      : "https://github.com/swcarpentry"
swc_installer   : "https://files.software-carpentry.org/SWCarpentryInstaller.exe"
swc_lessons     : "https://software-carpentry.org/v5/novice"
swc_site        : "https://software-carpentry.org"
swc_twitter     : "https://twitter.com/swcarpentry"
swc_vm          : "https://docs.google.com/uc?id=0B4Kr6DYkzkQtd05FekRId05DLXM&amp;export=download"
#--------------------------------------------------------------------------------
# Settings for Jekyll - should not need to be modified.
#--------------------------------------------------------------------------------
markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
exclude         : [tools]
